server:
  port: 8080
spring:
  datasource:
    username: root
    password: jliang83
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/mybatis_plus?characterEncoding=utf-8&useSSL=false